ZoneRegistry = {
  depot = {
    enabled=true,
    platforms={"1","2","3","4","5"},
    directions={}
  },
  dragonham={
    enabled=false,
    platforms={"1","2"},
    directions={"north","south"}
  },
  engine={
    enabled=true,
    platforms={"1","2","3","4","5","6","7","8","9"},
    directions={}
  },
  grimsgate={
    enabled=false,
    platforms={"1","2","3","4"},
    directions={"north","south"}
  },
  lukredes={
    enabled=false,
    platforms={"1","2"},
    directions={"north","south"}
  },
  malachite={
    enabled=true,
    platforms={"1","2","3","4"},
    directions={"north","south"}
  },
  savanna={
    enabled=false,
    platforms={"1","2","3","4"},
    directions={"north","south"}
  },
  shortlands={
    enabled=true,
    platforms={"1","2","3","4","bypass"},
    directions={"north","south"}
  },
  shrublands={
    enabled=false,
    platforms={"1","2","3","4"},
    directions={"north","south","east","west"}
  },
  sladenham={
    enabled=false,
    platforms={"1","2"},
    directions={"north","south"}
  },
  tooting={
    enabled=false,
    platforms={"1","2","3","4"},
    directions={"north","south"}
  }
}