zones/malachite/north/3.csv
zones/lukredes/north/1.csv
zones/shortlands/north/bypass.csv
zones/savanna/north/2.csv
zones/dragonham/north/1.csv
zones/shrublands/north/2.csv
zones/tooting/north/1.csv
zones/grimsgate/north/2.csv
zones/sladenham/north/2.csv