zones/malachite/south/3.csv
zones/lukredes/south/2.csv
zones/shortlands/south/bypass.csv
zones/savanna/south/3.csv
zones/dragonham/south/2.csv
zones/shrublands/south/1.csv
zones/tooting/south/2.csv
zones/grimsgate/south/3.csv
zones/sladenham/south/2.csv